use fm;
dfs -mkdir -p ${location};
create external table if not exists ${table_name} (IMSI_NO string, PHONE_NO string,GENDER string,BIRTHDAY string,AGE int,COUNTY_ID string,DISTRICT string,GROUP_CODE string,CORP_NAME string,INNET_MONTHS string,OPEN_TIME string,IS_GROUP_UNITS string,IS_VPMN_UNITS string,DYNAMIC_TYPE string,IS_VIP string,PAY_TYPE string,HURRY_MODE string,SM_NAME string,CREDIT_LEVEL string,XIANSHI_GPRS_NAME string,ADD_GPRS_NAME string,OVERFLOW string,IS_GPRS string,NATIONAL_ROAM_FEE double,NATIONAL_ROAM_FEE1 double,NATIONAL_ROAM_FEE2 double,SMS_FEE double,MMS_FEE double,TARIFF_FEE double,SHUJU_FEE double,LOCAL_FEE double,INTER_LONG_FEE double,SMS_PACKAGE double, LDTX string,LONG_FEE double,NATIONAL_LONG_FEE double,NATIONAL_LONG_FEE1 double,FLOW2 double,FLOW3 double,FLOW4 double,FLOW double,FLOW_WIFI double,IS_SMS_PACKAGE string,ARPU3_FEE double,ARPU3_CALLING_DURATIONS int,ARPU3_LOCAL_DURATIONS int,ARPU3_ROAM_DURATIONS int,ARPU3_LONG_DURATIONS int,ARPU3_SMS_CNT int,ARPU3_MMS_CNT int,ARPU3_FLOW_FEE double ,ARPU3_LOCAL_FEE double ,APPU3_ROAM_FEE double ,ARPU3_LONG_FEE double ,ARPU3_SMS_FEE double ,ARPU3_MMS_FEE double ,ARPU3_INTER_LONG_DURATIONS int,ARPU3_INTER_ROAM_DURATIONS int,ARPU3_INTER_LONG_FEE double,ARPU3_INTER_ROAM_FEE double,ONLINE_DAYS int,LAST_MOU_LEVEL int,LAST_GPRS_FLOW double,LAST_FLOW_EXC_CONTENT double,SMS_CNT int,MMS_CNT int,SHORT_NO string,PRODUCT_NAME string,BILL_CODE string,FLOW_PROP double,FLOW_PROP1 double,CALLING_NUMBER int,MIGU string,SJB string,SJYD string,SJYX string,SJSP string,G4_USER_FLAG string,V_BASIC_FEE string,IS_ONLINE string,IMEI_TIMES int,MACHINE_USE_TYPE string,IS_CONTRACT_MACHINE string,LAST_CHANGE string,IS_ZD_END string,IMEI_NO int,MACHINE_BRAND string,MACHINE_TYPE string,MACHINE_STANDARD string,OS_FLAG string,TD_SMART_FLAG string,ZD_END_TIME string,CALL_BUNDLE_FLAG string,MACHINE_BUNDLE_FLAG string,COMMODITY_BUNDLE_FLAG string,COMMODITY_LOW string,LOWFEE_END_TIME string,NET_ACTIVE_FLAG string) 
row format delimited
  fields terminated by '\001'
  COLLECTION ITEMS TERMINATED BY '\002'
  MAP KEYS TERMINATED BY '\003'
 STORED AS TEXTFILE
location '${location}';

insert overwrite table ${table_name}
	select a.imsi_no, a.PHONE_NO, a.GENDER, a.BIRTHDAY, a.AGE, a.COUNTY_ID, a.DISTRICT, a.GROUP_CODE, a.CORP_NAME, a.INNET_MONTHS, b.OPEN_TIME, b.IS_GROUP_UNITS, b.IS_VPMN_UNITS, b.DYNAMIC_TYPE, b.IS_VIP, c.PAY_TYPE, c.HURRY_MODE, c.SM_NAME, c.CREDIT_LEVEL, d.XIANSHI_GPRS_NAME, d.ADD_GPRS_NAME, d.OVERFLOW, d.IS_GPRS, d.NATIONAL_ROAM_FEE, d.NATIONAL_ROAM_FEE1, d.NATIONAL_ROAM_FEE2, d.SMS_FEE, d.MMS_FEE, d.TARIFF_FEE, d.SHUJU_FEE, d.LOCAL_FEE, d.INTER_LONG_FEE, d.SMS_PACKAGE, d.LDTX, d.LONG_FEE, d.NATIONAL_LONG_FEE, d.NATIONAL_LONG_FEE1, d.FLOW2, d.FLOW3, d.FLOW4, d.FLOW, d.FLOW_WIFI, d.IS_SMS_PACKAGE, d.ARPU3_FEE, d.ARPU3_CALLING_DURATIONS, d.ARPU3_LOCAL_DURATIONS, d.ARPU3_ROAM_DURATIONS, d.ARPU3_LONG_DURATIONS, d.ARPU3_SMS_CNT, d.ARPU3_MMS_CNT, d.ARPU3_FLOW_FEE, d.ARPU3_LOCAL_FEE, d.APPU3_ROAM_FEE, d.ARPU3_LONG_FEE, d.ARPU3_SMS_FEE, d.ARPU3_MMS_FEE, d.ARPU3_INTER_LONG_DURATIONS, d.ARPU3_INTER_ROAM_DURATIONS, d.ARPU3_INTER_LONG_FEE, d.ARPU3_INTER_ROAM_FEE, d.ONLINE_DAYS, d.LAST_MOU_LEVEL, d.LAST_GPRS_FLOW, d.LAST_FLOW_EXC_CONTENT, d.SMS_CNT, d.MMS_CNT, d.SHORT_NO, d.PRODUCT_NAME, d.BILL_CODE, d.FLOW_PROP, d.FLOW_PROP1, e.CALLING_NUMBER, e.MIGU, e.SJB, e.SJYD, e.SJYX, e.SJSP,  e.G4_USER_FLAG, e.V_BASIC_FEE, e.IS_ONLINE, f.IMEI_TIMES, f.MACHINE_USE_TYPE, f.IS_CONTRACT_MACHINE, f.LAST_CHANGE, f.IS_ZD_END, f.IMEI_NO, f.MACHINE_BRAND, f.MACHINE_TYPE, f.MACHINE_STANDARD, f.OS_FLAG, f.TD_SMART_FLAG, f.ZD_END_TIME, g.CALL_BUNDLE_FLAG, g.MACHINE_BUNDLE_FLAG, g.COMMODITY_BUNDLE_FLAG, g.COMMODITY_LOW, g.LOWFEE_END_TIME, g.NET_ACTIVE_FLAG from
	(select * from ${base_info_tmp}) a join
	(select * from ${client_identity_tmp}) b join
	(select * from ${crm_tmp}) c join
	(select * from ${teleservice_tmp}) d join
	(select * from ${uwi_tmp}) e join
	(select * from ${ueinfo_tmp}) f join
	(select * from ${consumer_behavior_tmp}) g
	on a.imsi_no=b.imsi_no and
	a.imsi_no=c.imsi_no and
	a.imsi_no=d.imsi_no and
	a.imsi_no=e.imsi_no and
	a.imsi_no=f.imsi_no and
	a.imsi_no=g.imsi_no;